/*
 * This file is generated by jOOQ.
 */
package com.jakub.todoSandbox.jooq;


import com.jakub.todoSandbox.jooq.tables.Step;
import com.jakub.todoSandbox.jooq.tables.Todo;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index IDX_STEP_TODO_ID = Internal.createIndex(DSL.name("idx_step_todo_id"), Step.STEP, new OrderField[] { Step.STEP.TODO_ID }, false);
    public static final Index IDX_TODO_NAME = Internal.createIndex(DSL.name("idx_todo_name"), Todo.TODO, new OrderField[] { Todo.TODO.NAME }, false);
}
