/*
 * This file is generated by jOOQ.
 */
package com.jakub.todoSandbox.jooq;


import com.jakub.todoSandbox.jooq.tables.Step;
import com.jakub.todoSandbox.jooq.tables.Todo;
import com.jakub.todoSandbox.jooq.tables.records.StepRecord;
import com.jakub.todoSandbox.jooq.tables.records.TodoRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<StepRecord> STEP_PKEY = Internal.createUniqueKey(Step.STEP, DSL.name("step_pkey"), new TableField[] { Step.STEP.ID }, true);
    public static final UniqueKey<TodoRecord> TODO_PKEY = Internal.createUniqueKey(Todo.TODO, DSL.name("todo_pkey"), new TableField[] { Todo.TODO.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<StepRecord, TodoRecord> STEP__STEP_TODO_ID_FKEY = Internal.createForeignKey(Step.STEP, DSL.name("step_todo_id_fkey"), new TableField[] { Step.STEP.TODO_ID }, Keys.TODO_PKEY, new TableField[] { Todo.TODO.ID }, true);
}
