/*
 * This file is generated by jOOQ.
 */
package com.jakub.todoSandbox.jooq;


import com.jakub.todoSandbox.jooq.tables.Step;
import com.jakub.todoSandbox.jooq.tables.Todo;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.step</code>.
     */
    public static final Step STEP = Step.STEP;

    /**
     * The table <code>public.todo</code>.
     */
    public static final Todo TODO = Todo.TODO;
}
