version: '3.8'

services:
  todo-app_container:
    image: 'lewandosiu/todo-backend:latest'
    container_name: todo-app_container
    ports:
      - "2052:8080"
    networks:
      - todo-net
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_container:5432/demoDB
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
networks:
  todo-net:
    external: true