/*
 * This file is generated by jOOQ.
 */
package com.jakub.todoSandbox.jooq.tables;


import com.jakub.todoSandbox.jooq.Keys;
import com.jakub.todoSandbox.jooq.Tododb;
import com.jakub.todoSandbox.jooq.enums.PriorityEnum;
import com.jakub.todoSandbox.jooq.tables.records.TodoRecord;

import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function4;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Todo extends TableImpl<TodoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>tododb.todo</code>
     */
    public static final Todo TODO = new Todo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TodoRecord> getRecordType() {
        return TodoRecord.class;
    }

    /**
     * The column <code>tododb.todo.id</code>.
     */
    public final TableField<TodoRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>tododb.todo.name</code>.
     */
    public final TableField<TodoRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>tododb.todo.description</code>.
     */
    public final TableField<TodoRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>tododb.todo.priority</code>.
     */
    public final TableField<TodoRecord, PriorityEnum> PRIORITY = createField(DSL.name("priority"), SQLDataType.VARCHAR.asEnumDataType(com.jakub.todoSandbox.jooq.enums.PriorityEnum.class), this, "");

    private Todo(Name alias, Table<TodoRecord> aliased) {
        this(alias, aliased, null);
    }

    private Todo(Name alias, Table<TodoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>tododb.todo</code> table reference
     */
    public Todo(String alias) {
        this(DSL.name(alias), TODO);
    }

    /**
     * Create an aliased <code>tododb.todo</code> table reference
     */
    public Todo(Name alias) {
        this(alias, TODO);
    }

    /**
     * Create a <code>tododb.todo</code> table reference
     */
    public Todo() {
        this(DSL.name("todo"), null);
    }

    public <O extends Record> Todo(Table<O> child, ForeignKey<O, TodoRecord> key) {
        super(child, key, TODO);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Tododb.TODODB;
    }

    @Override
    public Identity<TodoRecord, Long> getIdentity() {
        return (Identity<TodoRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<TodoRecord> getPrimaryKey() {
        return Keys.TODO_PKEY;
    }

    @Override
    public Todo as(String alias) {
        return new Todo(DSL.name(alias), this);
    }

    @Override
    public Todo as(Name alias) {
        return new Todo(alias, this);
    }

    @Override
    public Todo as(Table<?> alias) {
        return new Todo(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Todo rename(String name) {
        return new Todo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Todo rename(Name name) {
        return new Todo(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Todo rename(Table<?> name) {
        return new Todo(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, String, String, PriorityEnum> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function4<? super Long, ? super String, ? super String, ? super PriorityEnum, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function4<? super Long, ? super String, ? super String, ? super PriorityEnum, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
