/*
 * This file is generated by jOOQ.
 */
package com.jakub.todoSandbox.jooq.tables.records;


import com.jakub.todoSandbox.jooq.tables.Step;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StepRecord extends UpdatableRecordImpl<StepRecord> implements Record4<Long, String, String, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.step.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.step.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.step.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.step.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.step.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.step.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.step.todo_id</code>.
     */
    public void setTodoId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.step.todo_id</code>.
     */
    public Long getTodoId() {
        return (Long) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, String, String, Long> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Long, String, String, Long> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Step.STEP.ID;
    }

    @Override
    public Field<String> field2() {
        return Step.STEP.NAME;
    }

    @Override
    public Field<String> field3() {
        return Step.STEP.DESCRIPTION;
    }

    @Override
    public Field<Long> field4() {
        return Step.STEP.TODO_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getDescription();
    }

    @Override
    public Long component4() {
        return getTodoId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getDescription();
    }

    @Override
    public Long value4() {
        return getTodoId();
    }

    @Override
    public StepRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public StepRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public StepRecord value3(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public StepRecord value4(Long value) {
        setTodoId(value);
        return this;
    }

    @Override
    public StepRecord values(Long value1, String value2, String value3, Long value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StepRecord
     */
    public StepRecord() {
        super(Step.STEP);
    }

    /**
     * Create a detached, initialised StepRecord
     */
    public StepRecord(Long id, String name, String description, Long todoId) {
        super(Step.STEP);

        setId(id);
        setName(name);
        setDescription(description);
        setTodoId(todoId);
    }
}
